AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Cloudformation template'

# IAM User
Resources:
  MyIAMUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'DehanCFN'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'

# IAM Group

  MyIAMGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: 'DehanGroup'

# Attach User to Group

  UserToGroup:
    Type: 'AWS::IAM::UserToGroupAddition'
    Properties:
      GroupName: !Ref MyIAMGroup
      Users:
        - !Ref MyIAMUser

# IAM Role for EC2

  MyIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: ['ec2.amazonaws.com']
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/PowerUserAccess'

# S3 Custom Policy

  MyIAMPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: 'CustomPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action:
              - "s3:GetObject"
            Resource: '*'
      Roles:
        - !Ref MyIAMRole

