# CloudFormationTemplateVersion
# Description

AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cloudformation template for my third s3 bucket'
Resources:
  S3Bucket: 
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'dehanb-s3-bucket-yaml'
